language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: rudrigodevops
  api_key:
    secure: OoiljatAEzl1ODpgo0Rkq2hn6vmct7RuAw6QXKkKs3V4hGJ9Vo06FZvM8HTcfo+c+8dLlsDAb/UEoqE1mJFidGdSEmd7vjaFo+zgB2Tspgfh2ysUx8567+c4udUHRCw6UCPvAYgJWfiuhG59t0ET5VKcGbNqGIwBuWNSsZIBV9bnKdb6rBvCb+cXhWG7TAOnIl/JYCa2k15xOfLz/yh/dlqJpDfAr5nMgsknkhC0NRxLLO96yvLxEItIUktsaJbt+8YjAlno/9uCPxiIm5K0itOXlxzu1Z7HvBYcPUiGmACVHB/6fHWsERudABam23VMCoJNr8GWpPwBEtPiFzQjhmC+sfdn6Xfm671N0xHkKFXrgtTqkEJ90crEjxC9+J/K2u04ku0U23ChbiZO6YDwuF9y0HWyW8qa1FQZOBEAB1WptBXz8869WymKvQwCo0L34SKdkyERozVeeo8wBHxCIbDwyzOgV8zuqUPhirPIt9J7pFxCV8Cn1NOzx4CF/OvIxbpXQ8PUaW0WPSbE9ah7y4nMDOjtjXq4gppVPHlLx/Zh/tTRCr/SEj082p9Sm2dzcYk+UuciBqVFl9pVGM7eRN30tdkRVvDwNfr9CPbaoOikmq+N63FVPKnzSyaVk2jMgaSKzgcgm0X4DwAhKmt5KCbcLrJDIicrfdlzG4mnpXw=