language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: rudrigodevops
dd:
  secure: mAr1DCY11ya4I7+JzPYT6fOmUvFyZpiSVWrEb7qGen9/FR6BICFC/AIoOnKMdsvlkEJJL2NcKfe//dn48a3EZd56wMQHlUruW/vXWBNtdqJyt+RxpKyKX55XxCRG215pczyxyl8tMvoRSIvufjbF1bFMDnbjHk9SW2dgtjWkT/ffEpmmvQITbDkQTfvR6xm/B27v7msI+zNH2Z3mSqeISfoq0RAuLTGeLaeM7wfwjOsOMNFlG7a2FS+CfRnBwLG+PsR+c2MtVQlHydeTQLkeUKzjmquBc0ni4YKTARi8xmwR7OzoE0q1aEF2SzxyE/HLh+NQrqebKxOG7oNpwBfbneGBi7fWsO+OPBx0dUG2GzIJZ5xwyn8x3ssWieIh21R4sHq+vlbE8JUN+DjVizCgEx5uNIqQ0urxq1ZeE0FrHtr7q+PEzVYRklcQjNxWioA1LjQ/c+IC7VAVtI7JhDuRwlU1SVEgNqQP4/HfVzYTCDWafUk1DVvmnuIwWJg8TVFB9yMN2AtZkn9Rh555QikF6kt98O8GFE09/1fxxGzoLm6roYCwAPx5sz1SIbfkiqkPndO7+dWWVMfa/bCGOPQL0fY3PRsXfKVMbyhQkNuev8V4aYhBsieAut0QW9C+oW1TABbo7r5i8ocTiq1K/cEW+nb29GYenSaTnKlaTfWtwzw=
tr